version: '3.4'

services:   
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1337
      - POSTGRES_DB=PostItDb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  
  postitweb:
    build: .
    ports:
      - "8080:80"
    depends_on: 
      - postgres