version: '3.4'

services:
  postitdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1337
    ports:
      - '5432:5432'
    volumes:
      - postitdb:/var/lib/postgresql/data
  
  postit:
    image: ${DOCKER_REGISTRY-}postit
    build:
      context: PostIt.Web
      dockerfile: Dockerfile
    depends_on:
      - postitdb

volumes:
  postitdb:
    driver: local